#
#
#
debug: true

server:
    port: 8443
    ssl:
        key-store: classpath:keystore.p12
        key-store-type: PKCS12
        key-store-password: mypassword
        key-alias: tomcat

spring:
  thymeleaf:
    cache: false

zauth:
    clientId: yourClientId
    clientSecret: 'yourClientSecret' # we use 'ticks' here, because 'clientSecret' sometimes contains 'yaml-sensitive-tokens'

