#
#
#
debug: true

server:
    port: 8443
    ssl:
        key-store: classpath:keystore.p12
        key-store-type: PKCS12
        key-store-password: mypassword
        key-alias: tomcat

spring:
  thymeleaf:
    cache: false

logging:
  level:
    org.springframework: INFO
    org.springframework.social: DEBUG
    org.zalando.example: DEBUG
    org.apache.http: INFO
    org.apache.http.wire: INFO

zauth:
    clientId: yourClientId
    clientSecret: 'yourClientSecret' # we use 'ticks' here, because 'clientSecret' sometimes contains 'yaml-sensitive-tokens'
    credentialsDirectoryPath: ${user.dir}/credentials
    authorization-endpoint: https://sandbox.identity.zalando.com/oauth2/authorize
    token-endpoint: https://sandbox.identity.zalando.com/oauth2/token
    custom-params:
      business_partner_id: 810d1d00-4312-43e5-bd31-d8373fdd24c7

